### ISSUE TITLE
Consider transferring ownership of package

### ISSUE THREAD

**Issue by imhoffd** [ng-/ng#2]
Please consider relinquishing the `ng` package on npm. It hasn't been published in almost four years and is wildly out of date with Angular today.

1. The [Angular CLI](https://github.com/angular/angular-cli) provides the `ng` binary, but people often accidentally `npm install -g ng`. 
1. [`npx`](https://github.com/zkat/npx) is becoming a popular utility for running locally installed installed packages. It is now shipped with npm and also thus bundled with NodeJS. Another feature of npx [is this](https://github.com/zkat/npx#description):

    > By default, npx will check whether <command> exists in $PATH, or in the local project binaries, and execute that. If <command> is not found, it will be installed prior to execution.
    > 
    > Unless a --package option is specified, npx will try to guess the name of the binary to invoke depending on the specifier provided. 

    * This means people get this message:

        ```
        ❯ npx ng serve
        npx: installed 1 in 2.975s
        command not found: ng
        ```

This explains why this inactive package is being downloaded. People are doing this constantly, almost 2000 times a week and going up: https://npm-stat.com/charts.html?package=ng

@akircher

**Comment by akircher** [comment]
I would seriously consider a transfer request to the angular team or a popular open source package that is part of the broader community.  I am unwilling to unpublish to just let there be a land grab.

**Comment by imhoffd** [comment]
Thanks! 

@hansl @filipesilva Is this something the Angular team would be interested in?

At the very least, publishing an `index.js` script that runs this would be useful:

```js
console.error('You probably meant @angular/cli.');
process.exitCode = 1;
```

**Comment by filipesilva** [comment]
I hadn't considered the `npx` aspect myself but it is definitely a factor. @StephenFluin @robwormald WDYT? 

(Stephen and Rob are our DevRel folks and this feels like a question for them)

**Comment by StephenFluin** [comment]
Really great idea, and thanks for identifying that developers might be getting stuck trying to do the wrong thing.

I think we'd be happy taking on the namespace, but I don't believe we want to publish the CLI under a new name, so it would be as you said above, likely a warning that the user wanted something else, or a simple wrapper.  I'd put this back on @hansl and @igorminar for next steps for us to take on the namespace.

**Comment by hansl** [comment]
Hey @akircher,

You can shoot me an email at hansl@google.com, and we can setup the transfer. Shouldn't take more than 5 minutes :) Then I'll probably just release a package with that error above, and maybe longer term we can consider a better solution.

Cheers!

**Comment by hansl** [comment]
@akircher I haven't received any contact from you. Do you have time to discuss this?

**Comment by akircher** [comment]
@hansl Sorry for the delay. After some wrangling, I have permission from my team to publish the error code

```
console.error('You probably meant @angular/cli.');
process.exitCode = 1;
```

Hopefully, this will help most folks out.  Unfortunately, my team is less eager to transfer full ownership right now.  If this is important to your team, I would give it some time and then follow up with fleshed out proposal.

**Comment by akircher** [comment]
Error code published.  Thanks for the work that you all do!
